mainApp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title= StringField('Title', validators=[DataRequired()])
    content= TextAreaField('Content', validators=[DataRequired()])
    submit=SubmitField('Post')

mainApp/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from mainApp import db
from mainApp.models import Post
from mainApp.posts.forms import PostForm


posts= Blueprint('posts', __name__)
 
@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form=PostForm()
    if form.validate_on_submit():
        post=Post(title= form.title.data, content= form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Post has been created.", 'success')
        return redirect(url_for('main.index'))
    return render_template('new_post.html', form=form)


@posts.route('/post/<post_id>')
def post(post_id):
    post= Post.query.get_or_404(post_id)
    return render_template('post.html', post=post)


@posts.route('/post/<post_id>/update',methods=['GET', 'POST'])
def update_post(post_id):
    post= Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form=PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('new_post.html', form=form)
    
    
@posts.route("/post/<int:post_id>/delete", methods=['GET','POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.index'))

mainApp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from mainApp import db, bcrypt
from mainApp.models import User, Post
from mainApp.users.forms import (NameForm, LoginForm, UpdateAccountForm,
                                   requestResetForm, ResetPasswordForm)
from mainApp.users.utils import save_picture, send_reset_email




users= Blueprint('users', __name__)
 



@users.route('/form', methods=['GET', 'POST'])
def form():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form=NameForm()
    if form.validate_on_submit():
    # utf-8 for string instead of bytes
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        # using the database
        
        user=User(username=form.username.data, password= hashed_password, email=form.email.data)
        db.session.add(user)
        db.session.commit()

           
        msg=Message("Hi", sender='nityaak5@gmail.com', recipients=['nityaak5@gmail.com'])
        msg.body="Test Body"
        mail.send(msg)
        
        flash(f'Account created for {form.username.data}! You can now log in', 'success')
        return redirect(url_for("users.loginForm"))
        # return redirect(url_for('index',name=session.get('username'),kn=session.get('known',False)))
    return render_template('myform.html', form=form)



@users.route('/loginform', methods=['GET', 'POST'])
def loginForm():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page= request.args.get('next')   #to get profile, dont use square bracket with dict args- error. get gives none

            return redirect(next_page) if next_page else redirect(url_for("main.index"))
        
        else:
            flash('Incorrect Email or Password', 'danger')
    return render_template('loginForm.html', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form= UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file= save_picture(form.picture.data)
            current_user.image_file= picture_file

        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash("Details updated!", 'success')
        return redirect(url_for('users.profile'))
    elif request.method== 'GET':
        form.username.data= current_user.username
        form.email.data=current_user.email
    image_file= url_for('static', filename= 'profile_pics/'+ current_user.image_file)

    return render_template('profile.html', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_post(username):
    page=request.args.get('page',1, type=int)
    user=User.query.filter_by(username=username).first_or_404()
    posts=Post.query.filter_by(author=user)\
        .paginate(per_page=2, page=page)
    return render_template('user_post.html', posts=posts, user=user)





@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form= requestResetForm()
    if form.validate_on_submit():
        user= User.query.filter_by(email= form.email.data).first()
        send_reset_email(user)
        flash("Email Sent", "info")
        return redirect(url_for('users.loginForm'))


    return render_template('reset_request.html', form=form)



@users.route("/reset_password/<token>", methods=['GET', 'POST'])

def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    user= User.verify_reset_token(token)                         #will return a user id

    if user is None:
        flash("Invalid or expired token", 'warning')
        return redirect(url_for('users.reset_request'))
    form= ResetPasswordForm()
    if form.validate_on_submit():
      
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        # using the database
        
        user.password= hashed_password
   
        db.session.commit()
        
        flash(f'Updated', 'success')
        return redirect(url_for("users.loginForm"))
    return render_template('reset_token.html', form= form)

mainApp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" href="{{url_for('static', filename= 'styles.css')}}"> -->
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- <link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename= '/home/nityaa/Documents/Flask/Flask Form/static/styles.css')}}"> -->
   
    
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body style="background-color: #467a9e;">
        {% include 'navbar.html'%}
        <div class="container">
            
          <div class="col-md-6 offset-md-3">
            
            {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
         </div>
       
        {% block content %}{% endblock %}

      </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

mainApp/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}

{% block content %}


{% for post in posts.items %}
<div class="container mt-5 d-flex justify-content-center">
<div class= "card p-1 mx-auto">
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username)}}">{{ post.author.username }}</a>
    </div>
    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
</div>

</div>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
  {% if posts.page == page_num %}
    <a class="btn btn-info mb-4" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
  {% else %}
    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
  {% endif %}
{% else %}
  ...
{% endif %}
{% endfor %}
    
{% endblock content %}

mainApp/templates/loginForm.html
{% extends 'base.html' %}
{% block title %} Login Form {% endblock %}

{% block content %}
    
    <div class="content-section">
        <div class="row align-items-center">
            <div class="col-xs-1 center-block" style="text-align:center; margin-top: 30px">
            
                <h3>SIGN IN</h3>
             </div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            
                <br>
               
                <div class="col-md-6 offset-md-3">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <br>
                <div class="col-md-6 offset-md-3">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
                <br>
                <div class="d-grid gap-2 col-6 mx-auto"">
                    {{ form.submit(class="btn btn-light  btn-outline-info") }}
                </div>
                <br>
                <div class="col-xs-1 center-block" style="text-align:center;">
                
                Don't Have An Account? <a class="text-white" href="{{ url_for('users.form') }}"> Register </a>
                </div>

                <div class="col-xs-1 center-block" style="text-align:center;">
                
                    Forgot Password?  <a class="text-white" href="{{ url_for('users.reset_request') }}"> Reset </a>
                </div>
              
          
        
        </form>
    </div>
    </div>

{% endblock content %}

mainApp/templates/myform.html
{% extends 'base.html' %}
{% block title %} Form {% endblock %}

{% block content %}
    
    <div class="content-section">
        <div class="row align-items-center">
            <div class="col-xs-1 center-block" style="text-align:center; margin-top: 30px">
            
                <h3>SIGN UP</h3>
             </div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            
                <br>
                <div class="col-md-6 offset-md-3">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <br>
                <div class="col-md-6 offset-md-3">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <br>
                <div class="col-md-6 offset-md-3">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <br>
                <div class="col-md-6 offset-md-3">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            <br>
            <div class="d-grid gap-2 col-6 mx-auto"">
                {{ form.submit(class="btn btn-light  btn-outline-info") }}
            </div>
            <br>
            <div class="col-xs-1 center-block" style="text-align:center;">
            
               Already Have An Account? <a class="text-white" href="{{ url_for('users.loginForm') }}"> Sign In </a>
            </div>
          
        
        </form>
    </div>
    </div>

{% endblock content %}

mainApp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #86b9dd;">
    <div class="container-fluid">
        <div class="container">
            <a class="navbar-brand mx-auto" href="{{url_for('main.index')}}">Flask App</a>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
     
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
        
          {% if current_user.is_authenticated%}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.logout')}}">Log Out</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.profile')}}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('posts.new_post')}}">New Post</a>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.loginForm')}}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.form')}}">Form</a>
            </li>
          {% endif %}
        </ul>
        <!-- <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-light  btn-outline-info type="submit">Go</button>
          </form> -->
      </div>
    </div>
  </nav> 

mainApp/templates/new_post.html
{% extends 'base.html' %}
{% block title %} New Post {% endblock %}


{% block content %}
<div class="content-section">
        <div class="row align-items-center">
            <div class="col-xs-1 center-block" style="text-align:center; margin-top: 30px">
                <h3>New Post</h3>
             </div>
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                
                    <br>
                
                    <div class="col-md-6 offset-md-3">
                        {{ form.title.label(class="form-control-label") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <br>
                    <div class="col-md-6 offset-md-3">
                        {{ form.content.label(class="form-control-label") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    
                    <br>
                    <div class="d-grid gap-2 col-6 mx-auto"">
                        {{ form.submit(class="btn btn-light  btn-outline-info") }}
                    </div>
                    <br>
            </form>
    </div>
    </div>
{% endblock content %}

mainApp/templates/post.html
{% extends "base.html" %}
{% block title %}post{% endblock %}

{% block content %}
<div class="container mt-5 d-flex justify-content-center">
    <div class="card p-1">
        <div class="d-flex align-items-center mx-auto">
            
                
                <div class="row">
                    <a class="mr-2" href="{{url_for('users.profile')}}">{{ post.author.username }}</a>
                    {% if post.author == current_user %}
                    <div>
                      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                      <a class="btn btn-danger btn-sm mt-1 mb-1" href="{{ url_for('posts.delete_post', post_id=post.id) }}">Delete</a>
                    </div>
                  {% endif %}
                    
                    <h2 class="article-title">{{ post.title }}</h2>
                    <p class="article-content">{{ post.content }}</p>

                </div>
              
         
        </div>
    </div>
</div>

<!-- MODAL -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
                   


    
{% endblock content %}

mainApp/templates/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}


    <div class="container mt-5 d-flex justify-content-center">
        <div class="card p-1">
            <div class="d-flex align-items-center mx-auto">
                <div class="image"> <img src="{{image_file}}" class="rounded-circle" width="100"> </div>
                <div class="media-body">
                    <h4 class="ccount-heading">{{current_user.username}}</h4> 
                    <p class="text-secondary">{{current_user.email}}</p>
                </div>
            </div>
            <!-- ACCOUNT INFO FORM -->
            <div class="row align-items-center">
                <div class="col-xs-1 center-block" style="text-align:center; margin-top: 30px">
                    <h4>Account Info</h4>
                 </div>
                
                <form method="POST" action=""enctype="multipart/form-data">
                    {{ form.hidden_tag() }}

                        <div class="col-md-6 offset-md-3">
                            {{ form.username.label(class="form-control-label") }}
        
                            {% if form.username.errors %}
                                {{ form.username(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.username(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <br>
                        <div class="col-md-6 offset-md-3">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    <br>
                    <div class="col-md-6 offset-md-3">
                        {{ form.picture.label() }}
                        {{ form.picture(class= "form-control-file") }}
                        {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span><br>
                    {% endfor %}
                        {% endif %}
                    </div>
                    <br>

                    <div class="d-grid gap-2 col-6 mx-auto">
                        {{ form.submit(class="btn btn-light  btn-outline-info") }}
                    </div>
                </form>

                
            </div>
        </div>
    </div>
       
           
            





{% endblock %}

mainApp/templates/reset_request.html
{% extends 'base.html' %}
{% block title %} Password Reset {% endblock %}

{% block content %}
    
    <div class="content-section">
        <div class="row align-items-center">
            <div class="col-xs-1 center-block" style="text-align:center; margin-top: 30px">
            
                <h3>Reset Password</h3>
             </div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            
                <br>
               
                <div class="col-md-6 offset-md-3">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <br>
               
                <div class="d-grid gap-2 col-6 mx-auto"">
                    {{ form.submit(class="btn btn-light  btn-outline-info") }}
                </div>
 
         
        
        </form>
    </div>
    </div>

{% endblock content %}

mainApp/templates/reset_token.html
{% extends 'base.html' %}
{% block title %} Password Reset {% endblock %}

{% block content %}
    
    <div class="content-section">
        <div class="row align-items-center">
            <div class="col-xs-1 center-block" style="text-align:center; margin-top: 30px">
            
                <h3>Reset Password</h3>
             </div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            
                <br>
               
                <div class="col-md-6 offset-md-3">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <br>
                <div class="col-md-6 offset-md-3">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
               
                <div class="d-grid gap-2 col-6 mx-auto"">
                    {{ form.submit(class="btn btn-light  btn-outline-info") }}
                </div>
 
         
        
        </form>
    </div>
    </div>

{% endblock content %}

mainApp/templates/user_post.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}

{% for post in posts.items %}
<div class="container mt-5 d-flex justify-content-center">
<div class= "card p-1 mx-auto">
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username)}}">{{ post.author.username }}</a>
    </div>
    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
</div>

</div>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
  {% if posts.page == page_num %}
    <a class="btn btn-info mb-4" href="{{ url_for('users.user_post', username=user.username, page=page_num) }}">{{ page_num }}</a>
  {% else %}
    <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_post', username=user.username, page=page_num) }}">{{ page_num }}</a>
  {% endif %}
{% else %}
  ...
{% endif %}
{% endfor %}
    

{% endblock content%}